### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by StevenChoo** [humanswitch/consentcookie#47]
## Description
Currently all texts are in Duch and not other language is supported

## Expected Behavior
ConsentCookie should have the option to show texts in different languages. Also you should be able to update the language settings, so that you can toggle between different translations.

## Actual Behavior
No multi language support

**Comment by christianvriens** [comment]
![screen shot 2018-06-14 at 14 28 18](https://user-images.githubusercontent.com/10206234/41412120-45717202-6fdf-11e8-8d74-9605c7eced73.png)

Tested this in Chrome by putting a language in the settings advanced on top.  
Dutch: nl
English US: en-US
German: de

In Dutch I tested with an extra letter for the first word in the json, so the difference between standard CC and the text in the json would be visible. 

![screen shot 2018-06-14 at 14 35 31](https://user-images.githubusercontent.com/10206234/41412488-75bd833c-6fe0-11e8-9425-de297d10c614.png)


# Tests
- [x] Are for all the available fields the changes visible.
- [x] Does the text change to another language when selecting another default language in Chrome
- [x] Is the default dutch when the preferred chrome language is not available
Tested with only Russian in the preferred list
- [x] Expect Dutch translation because the preferred language Russian is not available. 
Tested with Russian preferred second 'en-US', third 'de' and fourth 'nl' 
- [x] Expect Dutch translation because the preferred language Russian is not available. In future the check might take into account that 'en-US' has a higher preference then 'nl'. Should be new improvement.
- [x] If not all the fields are available in the language are the other fields shown in the default language Dutch

**Comment by christianvriens** [comment]
My suggestion with with previous comment: If text with questionmark isn't used remove it. 
https://github.com/humanswitch/consentcookie/issues/47#issuecomment-397280111

**Comment by christianvriens** [comment]
@StevenChoo shouldn't the field 'general': 'moreinfo' be with 'consent'?

And if this is changed will existing users still be able to use this in CC?
❓ create improvement issue for this

**Comment by StevenChoo** [comment]
> @StevenChoo shouldn't the field 'general': 'moreinfo' be with 'consent'?

>And if this is changed will existing users still be able to use this in CC?
>question create improvement issue for this

Need to check this out

**Comment by StevenChoo** [comment]
> My suggestion with with previous comment: If text with questionmark isn't used remove it.
#47 (comment)

All text referenced in the config are beeing used. If not its a bug.

**Comment by StevenChoo** [comment]
> question close: 'Sluiiten',
Removed from default config due to not beeing used.

> question gdpr: 'RRecht op...',
Is used for the link shown at every application for requesting GDPR actions. It is only shown when the GDPR option is used

![image](https://user-images.githubusercontent.com/8590349/41420160-277c32fe-6ff4-11e8-913c-7ab32a65b10f.png)

> question moreInfo: 'mMeer informatie over deze applicaties',
> question moreInfoLink: 'https://www.consentcookie.eu',

It seems to be removed since v0.6.0

![image](https://user-images.githubusercontent.com/8590349/41421116-523573c8-6ff6-11e8-8907-6cdb4047f06a.png)

Created issue for this: #58

**Comment by StevenChoo** [comment]
Fixed
